# Generated by Django 5.2.6 on 2025-11-17 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('username', models.CharField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=254)),
                ('last_name', models.CharField(max_length=254)),
                ('phone', models.CharField(max_length=24)),
                ('city', models.CharField(max_length=254)),
                ('county', models.CharField(max_length=254)),
                ('departament', models.CharField(max_length=254)),
                ('role', models.CharField(max_length=254)),
                ('birth_date', models.DateField(null=True)),
                ('salary', models.IntegerField()),
                ('is_staff', models.BooleanField(blank=True, null=True)),
                ('date_joined', models.DateField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
