# Generated by Django 5.2.6 on 2025-11-17 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='county',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='departament',
            new_name='department',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
